### ISSUE TITLE
Enable picky mode

### ISSUE THREAD

**Issue by mwip** [PillFall/Emacs-LanguageTool.el#18]
First, thanks for the awesome work on this, driving OSS language checking in Emacs forward. I deeply appreciate your work and use `languagetool.el` every day. This is not specifically a bug, maybe it is better classified as "question", "enhancement" or "config".

In the LT browser plugins one can enable "picky" mode which will help you catch some style issues.
| Settings | In action |
|------|------|
|![image](https://user-images.githubusercontent.com/29728338/221118823-c6116468-ba5b-4927-9204-1017c3cf0cea.png) |![image](https://user-images.githubusercontent.com/29728338/221119286-4d2ce1dd-1f64-430e-a6e1-c03c8b25ddc2.png) |

Is there any way to enable this in `languagetool.el`, or is this very specific to the browser plugin?

**Comment by PillFall** [comment]
Sorry for the late response, I do not want to give a wrong answer.

You can activate the **picky** level in `console` mode only(will change in the future) using:
```elisp
(setq languagetool-console-arguments '("--level" "PICKY")) 
```

**Comment by mwip** [comment]
Thanks for your answer. I am using `server` mode, though (with a local server). Is it possible to use `picky` mode with that as well. Unfortunately, I did not find any documentation at upstream LT docs.

**Comment by PillFall** [comment]
> Thanks for your answer. I am using `server` mode, though (with a local server). Is it possible to use `picky` mode with that as well. Unfortunately, I did not find any documentation at upstream LT docs.

Yeah, you could do that via the level query parameter in the server request, right now there is no support for this feature. But will add in a couple days 😁

**Comment by PillFall** [comment]
@mwip All set, you can now use this feature in [v1.3.0](https://github.com/PillFall/languagetool.el/releases/tag/v1.3.0)

Sorry for being slow, just started the university test that week :neutral_face:

**Comment by mwip** [comment]
Thank you so much for this fix! This is really improving LT for Emacs once more. I really appreciate your effort and wish you all the best for uni! Keep up the good work :+1:
