### ISSUE TITLE
Can it use languagetool command line instead of language-tool.jar ?

### ISSUE THREAD

**Issue by lakkiy** [PillFall/Emacs-LanguageTool.el#4]

**Comment by PillFall** [comment]
Sorry. I don't get what do you mean or trying to do. Can you please reformulate your question?

**Comment by lakkiy** [comment]
I don't want to download languagetool-commandline.jar, but I can install it via brew install languagetool and use command languagetool in terminal, can this package use this instead of setting languagetool-commandline.jar?

**Comment by PillFall** [comment]
Ok, if I'm not wrong, when you download and install LanguageTool from Homebrew, the installation take the same path as when you install it from `pacman` in ArchLinux, you get all the class files (including `languagetool-commandline.jar`) and then Homebrew creates a wrapper executable to call all the files in the correct order (notice that the package depends on JRE In Homebrew page). So I suggest you to try to find the class files and use the same configuration as in #3. I wait for your response.

SN. I don't have a Mac so testing from my side would be pretty hard. Although I will try to do it on a loaned machine.

**Comment by PillFall** [comment]
Doing a little research through Homebrew formula for LanguageTool, I find that the files where put in the `libexec` directory.
