### ISSUE TITLE
Is it possible to only use the http langtool server? How can I debug LanguageTool returned with status 1

### ISSUE THREAD

**Issue by contra-bit** [PillFall/Emacs-LanguageTool.el#5]
I start my languagetool on boot with systemd. 
```
LanguageTool returned with status 1

Jun 24 16:41:04 NAME languagetool[49404]: WARN  o.l.language.LanguageIdentifier Cannot consider noopLanguages because not in fastText mode: [en, de]
```

These are the only error messages I have recived

**Comment by PillFall** [comment]
Yeah, you can use a standalone or already created HTTP Server. You only need to config the URL and Port. There is no need to start the server from Emacs. This was solved in [v0.4.0](https://github.com/PillFall/Emacs-LanguageTool.el/releases/tag/v0.4.0).

In your `.emacs` you only need to add:

```elisp
(setq languagetool-server-url "http://whateverlocation") ;; without trailing forward slash

(setq languagetool-server-port 8081) ;; The port to the server.
;; If you access through http://localhost/api/v2/check for example. This should be set to 80
```

Then you can check the buffer using `languagetool-server-mode`

P.S. If you are having trouble with the init of LanguageTool Server from `systemd`. I suggest you to post a issue in LanguageTool GitHub page ([link](https://github.com/languagetool-org/languagetool))

**Comment by PillFall** [comment]
As I get no response and this must be invalid (you are referring to the behavior of LanguageTool itself, not to the Emacs package). I'm going to close and mark the issue as invalid.

**Comment by marcfargas** [comment]
> ```emacs-lisp
> (setq languagetool-server-url "http://whateverlocation") ;; without trailing forward slash
> 
> (setq languagetool-server-port "8081") ;; The port to the server.
> ;; If you access through http://localhost/api/v2/check for example. This should be set to 80
> ```

Note that the port has to be a number:

```emacs-lisp
(setq languagetool-server-url "http://whateverlocation") ;; without trailing forward slash
(setq languagetool-server-port 8081) ;; The port to the server.
```

Otherwise, you will be greeted with: 

> languagetool-server-mode-on: Format specifier doesn’t match argument type
