### ISSUE TITLE
use-package

### ISSUE THREAD

**Issue by CDitzel** [PillFall/Emacs-LanguageTool.el#6]
thank you for this package!

I am using use-package in my config. How can I install this package ? 

Thank you in advance

**Comment by PillFall** [comment]
Hi.

**Comment by PillFall** [comment]
Hi.

First of all, you should install it via MELPA, it's the easiest way to do it. Also install Java and download LanguageTool binaries.

If you download the binaries from the LanguageTool download page, then you could unzip that into a folder like `~/.languagetool`.

Then in your `.emacs` you should write something like in #3:
```elisp
(use-package languagetool
  :ensure t
  :defer t
  :commands (languagetool-check
	     languagetool-clear-buffer
	     languagetool-correct-at-point
	     languagetool-correct-buffer
	     languagetool-set-language)
  :config
  (setq languagetool-language-tool-jar "~/.languagetool/languagetool-commandline.jar"
	languagetool-server-language-tool-jar "~/.languagetool/languagetool-server.jar"
	languagetool-java-arguments '("-Dfile.encoding=UTF-8")
	languagetool-default-language "en-GB"))
```

And that should be enought to use this package.

**Comment by ram535** [comment]
These instructions should be in the readme.

**Comment by PillFall** [comment]
Yeah, you're right, I planned to upgrade and do a full refactoring of everything (including docs and doc strings) as at the moment the package is performing pretty poorly (at least for my liking). And, I want to include a module to exclude markup tokens.
